version: 0.2
env:
    parameter-store:
        TEST_KEY_FOR_PIPELINE: TEST_KEY_FOR_PIPELINE
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install typescript -g
      - npm install jest -g
  build:
    commands:
      - echo Build Started
      - npm run build
artifacts: 
  files:
    - package.json
    - package-lock.json