version: 0.2
env:
    parameter-store:
        TEST_KEY_FOR_PIPELINE: TEST_KEY_FOR_PIPELINE
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - export PORT=4500
      - export TEST_KEY_FOR_PIPELINE=$TEST_KEY_FOR_PIPELINE
  build:
    commands:
      - echo Build started on `date`
      - echo Building the production Docker image...
      - docker build -t pipeline-test .
      - docker tag pipeline-test:latest 754461976050.dkr.ecr.eu-central-1.amazonaws.com/pipeline-test:latest
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push 754461976050.dkr.ecr.eu-central-1.amazonaws.com/pipeline-test:latest