version: 0.2
env:
    parameter-store:
        TEST_KEY_FOR_PIPELINE: TEST_KEY_FOR_PIPELINE
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - export PORT=4500
      - export TEST_KEY_FOR_PIPELINE=$TEST_KEY_FOR_PIPELINE
  build:
    commands:
      - echo Build started on `date`
      - echo Building the production Docker image...
      - docker build -t 754461976050.dkr.ecr.eu-central-1.amazonaws.com/pipeline-test/pipeline-test:latest .
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push 754461976050.dkr.ecr.eu-central-1.amazonaws.com/pipeline-test/pipeline-test:latest