version: '3.8'
services:
    ysi_admin_api:
        container_name: ysi_admin_api
        image: ysi_admin_api
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:debug
        networks:
            - ysi-admin-network
        volumes:
            - ./packages/api/:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - mysql57
        links:
            - "mysql57:db"
        environment:
            - PORT=8080
            - TYPEORM_CONNECTION=mysql
            - TYPEORM_HOST=db
            - TYPEORM_USERNAME=root
            - TYPEORM_PASSWORD=root
            - TYPEORM_DATABASE=admindb
            - TYPEORM_PORT=3306
            - TYPEORM_LOGGING=true
            - TYPEORM_ENTITIES=**/dist/src/entities/*.{.ts,.js}
            - TYPEORM_MIGRATIONS=migrations/*.ts
            - TYPEORM_SYNCHRONIZE=false
            - NODE_ENV=development
            - GOOGLE_CLIENT_ID=24saatteis_google_client_id
            - GOOGLE_GOOGLE_SECRET=GOOGLE_GOOGLE_SECRET
            - GOOGLE_CALLBACK_URL=GOOGLE_CALLBACK_URL
    ysi_admin_ui:
        container_name: ysi_admin_ui
        image: ysi_admin_ui
        build:
            context: ./packages/ui
            dockerfile: Dockerfile
        command: yarn start
        ports: 
            - 3000:3001
        networks:
            - ysi-admin-network
        volumes:
            - ./packages/ui/:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        environment:
            - PORT=3001
            - REACT_APP_GRAPHQL_URI=http://localhost:80/api/graphql
    mysql57:
        container_name: ysi_admin_db
        image: mysql:5.7
        ports:
            - 3306:3306
        networks:
            - ysi-admin-network
        volumes:
            - db:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: admindb
            MYSQL_PASSWORD: root
        restart: unless-stopped
    nginx: 
        image: bitnami/nginx:latest
        container_name: ysi_admin_webserver
        networks:
            - ysi-admin-network
        depends_on:
            - ysi_admin_api
            - ysi_admin_ui
        links:
            - "ysi_admin_api:api"
            - "ysi_admin_ui:ui"
        volumes:
            - ./nginx/nginx.conf/:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro  
        ports:
            - 80:80
networks:
    ysi-admin-network:
volumes:
    db: